### PR TITLE
Add order statistics checks

### PR DESCRIPTION
**Pull request by mj-will**
Add the nested sampling cross-checks using order statistics that are described in: https://arxiv.org/abs/2006.03371

The test checks if the distribution of indices of each newly inserted live point with respect to the existing live points is uniform using the likelihood as the ordering criteria and produces a KS-statistic and p-value.

### CODE REVIEW

**Comment by mj-will** [comment]
This is currently missing the Bonferroni correction for multiple testing that is used in the paper to combine the rolling p-values

**Comment by johnveitch** [comment]
@mj-will Is this ready to merge? I see that you were changing some internal arrays of samples - is that necessary?

**Comment by mj-will** [comment]
@johnveitch, I'll need to take another look at this. I had to change things to avoid sorting the samples every time a new live point is inserted. It's correctly implemented in FlowProposal but there a small differences here because of the multiple threads.

**Comment by johnveitch** [comment]
@mj-will Could you take a look at the conflicts? They don't seem too difficult to solve and it'd be good to get this merged in.

**Comment by mj-will** [comment]
@johnveitch sure thing. Other than the conflicts I think there was an issue with how it computed the indices when using more than 1 thread. I'll try to look into it over the next week.

**Comment by mj-will** [comment]
There are few things left that I think need to be done before merging this:

- [x] Verify that the KS is correct for the distribution of live points and returns low p-values when distribution is not uniform
- [ ] Agree on maximum number of bins for indices plot
- [x] Compare output from before and after changes
- [ ] Choose how behaviour relates to verbosity

Let me know if anything else comes to mind.

**Comment by mj-will** [comment]
@johnveitch I think this is ready to merge, excluding any changes you'd like made. I've compared results between the tests before and after these changes and I can't see any obvious issues but it's probably worth double-checking.

There are two points in my previous comment that could easily be changed:
* the maximum number of bins for the indices histogram is 30
* the plotting triggers with `verbose >= 2` and the KS test is computed for all values of `verbose`

Let me know what you think.

**Review by wdpozzo — COMMENTED** [review]
Hi @mj-will I had a look at your changes and they seem ok to me. I have a question:
how much does it help not having to sort the live points at each step? 
Also, while i think this can be merged, I will bounce  this to @johnveitch for the final approval.

**Review by johnveitch — COMMENTED** [review]
LGTM

**Review by johnveitch — APPROVED** [review]

**Comment by mj-will** [comment]
> Hi @mj-will I had a look at your changes and they seem ok to me. I have a question:
> how much does it help not having to sort the live points at each step?

Hi @wdpozzo, when running the scripts in `tests` the difference seems to be minimal. I think they're too short to really notice anything. I also compared results using `rosenbrock.py` and there appeared to be roughly a 10% improvement but there's also quite a lot of variability between runs, so it's hard to say for sure.

**Comment by wdpozzo** [comment]
Hi @mj-will, thank you. I am going to port your PR also to the rework branch, where the live points are managed differently and the increase in performance should become more apparent.

**Comment by wdpozzo** [comment]
@mj-will I incorporated your pull request in the rework branch and it seems to give a bit of improvement indeed. I think I got it right, but if you feel like, please check that branch out.

**Pull request merged**
