### PR TITLE
Overhead is a misleading name

### PR DESCRIPTION
**Pull request by wdpozzo**
This pull requests changes the sampler philosophy as follows: 

the sampler is always looping over the whole ensemble and updating it all. Nmcmc refers to the number of jump each individual evolution point has to take before getting put back in the stack. The new live point is proposed starting from a random chosen one from the stack. 

Introduces the output of the single mcmc chains in separate files to be used as posterior samples
The code successfully passes the 1D and 2D tests as well as the 50D. The efficiency of the code is increased by about 1 order of magnitude and ACL are reduced dramatically. No user model changes are necessary. Note that the number of evolution points is critical for a correct sampling.

### CODE REVIEW

**Comment by johnveitch** [comment]
I see some failures of the analytic evidence tests when I run setup.py test. I'll take a look and see if I can work out what's going on.

**Comment by wdpozzo** [comment]
ah, that's weird. it passes for me. i will also have a look and try to understand

**Review by johnveitch — COMMENTED** [review]
I'm not clear on what the new philosophy is, can you summarise it? Looks like the MCMC threads store their own chains internally?

**Comment by wdpozzo** [comment]
yes, the MCMC samples are stored in the object and output at the end of the run. it is missing a post-processing step to resample them

**Pull request merged**
