### PR TITLE
Internal storage

### PR DESCRIPTION
**Pull request by wdpozzo**
This fixes the conversion between Live point and numpy structured arrays and automatically provides a numpy structured array as nested sampling chain output without having to read the samples from file.

### CODE REVIEW

**Comment by johnveitch** [comment]
This is giving me some weird looking posteriors. Somehow I think the samples must be being fed to nest2pos wrongly.
posterior

**Comment by wdpozzo** [comment]
yup, it looks like it is not receiving the end of the chain, actually

**Comment by wdpozzo** [comment]
Cannot see anything wrong though, and the np array seems correct after the stacking in 
`self.nested_samples = rfn.stack_arrays([self.NS.nested_samples[j].asnparray() for j in range(len(self.NS.nested_samples))],usemask=False)`

**Comment by wdpozzo** [comment]
Actually, how is logZ? It also seems wrong:

> Final evidence: -3.01
> Information: 1.60
> Saved nested sampling plot as ./chain_500_1234.txt.png
> Computed log_evidences: (-6.5689353389471474,)

**Comment by wdpozzo** [comment]
Ok, i think I understand what is going on and my last commit fixes it. when creating the structured array, the initial field is not the dimension of the problem, but it always needs to be 1 which is the number or rows in the array. adding more than 1 will simply duplicate the entries. 
The evidence and normality of the posteriors passes. Can you verify your plot again with this fix?

**Comment by johnveitch** [comment]
Looks like that solved it. Thanks!

**Pull request merged**
