### PR TITLE
Proposals to be object oriented

### PR DESCRIPTION
**Pull request by johnveitch**
I tweaked the proposals so they are proper classes and the arguments do not need to be carried around by the sampler. This should improve the modularity of the code and make it easier to add, remove or test proposals.

### CODE REVIEW

**Review by wdpozzo — COMMENTED** [review]
I see you changed essentially everything about the proposals and migrated from a cython implementation to a pure python one. Before I approve this, did you check how the performance is affected?

**Comment by johnveitch** [comment]
[prof_newprop.txt](https://github.com/johnveitch/cpnest/files/778338/prof_newprop.txt)
[prof_oldprop.txt](https://github.com/johnveitch/cpnest/files/778339/prof_oldprop.txt)

Hmm, it's quite a bit slower. Looks like numpy.random.choice is bizarrely slow. I'll work on it some more and get back to you

**Comment by johnveitch** [comment]
After some profiling and optimisation this version is about 20% faster than the cython one.

**Comment by wdpozzo** [comment]
I did run a few tests, and i noticed that on the test_gaussian.py the algorithm behaves weirdly. It seems unable to find new points and logL seems not to increase. I checked and apparently the increase is beyond the printing digits, so no problem there. Maybe should merge with master?

**Pull request merged**
