### PR TITLE
WIP: Fixing logging for improved compatibility with other packages

### PR DESCRIPTION
**Pull request by alexlyttle**
Solves to Issue #78.

- Adds `utils.py`
    - Adds some logging handler classes with the ability to set verbosity to emulate behaviour prior to this PR.
    - Adds the `LogFile` class which is a context manager for logging to a file. Again, this emulates behaviour prior to this PR.
    - Adds a `log_file` attribute to the `CPNest` class to enable file logging with the context manager in the `__init__` and `run` functions. 
 - Follows recommended naming convention for loggers in each module.
 - Adds a global package logger named `'cpnest'` defined in `__init__.py`. All module and class loggers inherit settings from this logger

I couldn't seem to get the tests running on my clone of `johnveitch/cpnest` so I'm not sure how best to check that my changes produce the expected output and don't interfere with other `cpnest` operations. What would you recommend?

### CODE REVIEW

**Comment by johnveitch** [comment]
Hi @alexlyttle thanks! Don't worry about the PEP8 issues. I'll just try running the tests here. Out of interest, what goes wrong with `python3 setup.py test`?

**Comment by alexlyttle** [comment]
Oh I just fixed a little bug in the last commit.

When I run `python3 setup.py test` I get a series of `EOFError` for each test both on the `master` branch and my `issue78` branch. 

**Example**:

```python
======================================================================
ERROR: test_run (tests.test_2d.GaussianTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ajl573/Repos/alexlyttle/cpnest/tests/test_2d.py", line 31, in setUp
    self.work=cpnest.CPNest(gaussmodel,verbose=2,nthreads=1,nlive=1000,maxmcmc=5000,poolsize=1000)
  File "/Users/ajl573/Repos/alexlyttle/cpnest/cpnest/cpnest.py", line 156, in __init__
    self.manager.start()
  File "/Users/ajl573/Repos/alexlyttle/cpnest/cpnest/cpnest.py", line 537, in start
    super(RunManager, self).start()
  File "/Users/ajl573/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Users/ajl573/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/ajl573/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/ajl573/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by johnveitch** [comment]
Heh I just spotted that filename issue too. That's strange about failing to run the tests. I will see if I can get someone else to reproduce because it's OK for me on Linux.  The changes look good, I will merge the request. Thanks!

**Comment by alexlyttle** [comment]
Thanks for checking and merging! That may make it MacOS specific, so I will look into this a little further in case it's an issue with my Python environment.

**Pull request merged**
