### PR TITLE
Testing evidence evaluation with the 1d Gaussian model

### PR DESCRIPTION
**Pull request by mattpitkin**
Here's the start of my testing cpnests evidence estimation for the different proposals when using the simple 1D Gaussian likelihood.

To do this I've had to make some changes to the CPNest and Sampler class initialisations, which you may or may not want to implement in the production code. I've allowed you to input lists of the proposal names and weights that you want to use (this isn't done very elegantly at the moment!), and the `poolsize` to use for the ensemble, when initialising the CPNest class. This allows me to test thing more easily against what I see with the `LALInference` sampler (for which the poolsize is the number of live points by default).

There is also a `test_1d_walk.py` script in which I define the 1d Gaussian with a given prior bound range and run the nested sampling 20 times. For the case of just using the ensemble walk proposal, 512 live points (and the same number of pool points), and a KL divergence between the prior and posterior of 8.5 nats, I find that the estimated evidence is actually consistent with the true analytical evidence (the log of the ratio has a small mean, approx -0.1, and a standard deviation that very well matches that estimated from sqrt(information/Nlive)). This is inconsistent with what I was seeing from the `LALInference` version shown in this [plot](https://github.com/mattpitkin/CW_nested_sampling_doc/blob/master/figures/proptesting/walk_prop/evidences/collate_plots_wp_evidences.png).

There is some evidence that there are still problems if I leave the default pool size as 100, but I'll need to do some more testing (with different KL divergence ranges and numbers of live points). Feel free to play around with the test to.

### CODE REVIEW

**Comment by johnveitch** [comment]
Hi Matt, I did some runs with this test and the evidence seems to be bang on using the EnsembleWalk proposal at least. Is this the prior range that you would expect difficulties to show up? What I could do is add it as a test for each of the proposals to check them all individually.

**Comment by mattpitkin** [comment]
I think the prior range in the test corresponds to the values at 8.5 nats on the upper x-axis in [this plot](https://github.com/mattpitkin/CW_nested_sampling_doc/blob/master/figures/proptesting/walk_prop/evidences/collate_plots_wp_evidences.png). So, for 512 live points nested sampling, as in LALInference, gives 0.5 offset in the log evidence, whereas for 8192 live points it's on average about 1.3 off.

Have you checked when using the default of 100 pool points, rather than my change to use the full number of live points? It looks like there must be some slight difference within the LALInference version that's causing the issue!

**Comment by mattpitkin** [comment]
One difference I can see between cpnest and the nested sampler in LALInference is that in cpnest the pool of points for the sample is updated after every N/10 points, _or_ if the acceptance drops below 0.01. The later rule isn't in the LALInference version. Could this make a difference? Or, are there other more obvious differences?

**Comment by mattpitkin** [comment]
The analytical KL divergence calculating in this branch wrong, so needs to be corrected.

**Comment by mattpitkin** [comment]
Just going to close this. I think it's something that will probably be tested via bilby when the review of that expands to cover more samplers.

**Pull request closed without merging**
